kind: pipeline
type: docker
name: default

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.13
  commands:
  - make test

- name: lint
  image: golang:1.13
  commands:
  - make lint

- name: manager-testing
  image: golang:1.13
  commands:
  - go test -v ./pkg/manager -test.long
  when:
    branch:
      - master
    event:
      - pull_request

- name: release
  image: golang:1.13
  when:
    branch:
    - master
    event:
    - tag
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    PACKAGECLOUD_TOKEN:
      from_secret: packagecloud_token
  commands:
  - curl -sL https://git.io/goreleaser | bash
  - curl -F "package[distro_version_id]=190" -F "package[package_file]=@$(ls dist/e2d_*_x86_64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/criticalstack/public/packages.json
  - curl -F "package[distro_version_id]=204" -F "package[package_file]=@$(ls dist/e2d_*_x86_64.rpm)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/criticalstack/public/packages.json
