# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  # Ensure that any go.mod modifications due to linters, go generate, etc are
  # removed.
  - go mod tidy
  # Using Go modules intrinsically causes modifications to these files that are
  # unfortunately unavoidable. Newer patch versions available to the CI will
  # satisfy the same module requirements and cause additions to go.sum.
  - git checkout -- go.sum
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=direct
  - GOSUMDB=off
  main: ./cmd/e2d
  goarch:
  - "386"
  - amd64
  - arm64
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}
  asmflags:
    - all=-trimpath={{.Env.GOPATH}}
  ldflags:
     - -s -w
     - -X "github.com/criticalstack/e2d/internal/buildinfo.Date={{.Date}}"
     - -X "github.com/criticalstack/e2d/internal/buildinfo.GitSHA={{.ShortCommit}}"
     - -X "github.com/criticalstack/e2d/internal/buildinfo.Version={{.Tag}}"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/criticalstack/e2d
  description: Cloud-native etcd management
  maintainer: criticalstack <dev@criticalstack.com>
  license: Apache-2.0
  vendor: criticalstack
  bindir: "/usr/local/bin"
  replacements:
    amd64: x86_64
  formats:
  - deb
  - rpm
  conflicts:
  - etcd
  empty_folders:
  - /etc/systemd/system/e2d.service.d
  - /var/lib/etcd
  files: 
    build/e2d.service: /etc/systemd/system/e2d.service
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
