# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  # Ensure that any go.mod modifications due to linters, go generate, etc are
  # removed.
  - go mod tidy
  # Using Go modules intrinsically causes modifications to these files that are
  # unfortunately unavoidable. Newer patch versions available to the CI will
  # satisfy the same module requirements and cause additions to go.sum.
  - git checkout -- go.sum
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=direct
  - GOSUMDB=off
  main: ./cmd/e2d
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}
  asmflags:
    - all=-trimpath={{.Env.GOPATH}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
